// Mocks generated by Mockito 5.1.0 from annotations
// in ditonton/test/presentation/bloc/tvseries_detail_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:ditonton/common/failure.dart' as _i6;
import 'package:ditonton/domain/entities/tvseries.dart' as _i9;
import 'package:ditonton/domain/entities/tvseries_detail.dart' as _i7;
import 'package:ditonton/domain/repositories/tvseries_repository.dart' as _i2;
import 'package:ditonton/domain/usecases/get_tvseries_detail.dart' as _i4;
import 'package:ditonton/domain/usecases/get_tvseries_recommendations.dart'
    as _i8;
import 'package:ditonton/domain/usecases/get_watchlist_status_tvseries.dart'
    as _i10;
import 'package:ditonton/domain/usecases/remove_watchlist_tvseries.dart'
    as _i12;
import 'package:ditonton/domain/usecases/save_watchlist_tvseries.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeTvseriesRepository_0 extends _i1.Fake
    implements _i2.TvseriesRepository {}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

/// A class which mocks [GetTvseriesDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvseriesDetail extends _i1.Mock implements _i4.GetTvseriesDetail {
  MockGetTvseriesDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvseriesRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvseriesRepository_0()) as _i2.TvseriesRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.TvseriesDetail>> execute(int? id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
              returnValue:
                  Future<_i3.Either<_i6.Failure, _i7.TvseriesDetail>>.value(
                      _FakeEither_1<_i6.Failure, _i7.TvseriesDetail>()))
          as _i5.Future<_i3.Either<_i6.Failure, _i7.TvseriesDetail>>);
}

/// A class which mocks [GetTvseriesRecommendations].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvseriesRecommendations extends _i1.Mock
    implements _i8.GetTvseriesRecommendations {
  MockGetTvseriesRecommendations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvseriesRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvseriesRepository_0()) as _i2.TvseriesRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i9.Tvseries>>> execute(dynamic id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
              returnValue:
                  Future<_i3.Either<_i6.Failure, List<_i9.Tvseries>>>.value(
                      _FakeEither_1<_i6.Failure, List<_i9.Tvseries>>()))
          as _i5.Future<_i3.Either<_i6.Failure, List<_i9.Tvseries>>>);
}

/// A class which mocks [GetWatchListStatusTvseries].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchListStatusTvseries extends _i1.Mock
    implements _i10.GetWatchListStatusTvseries {
  MockGetWatchListStatusTvseries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvseriesRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvseriesRepository_0()) as _i2.TvseriesRepository);
  @override
  _i5.Future<bool> execute(int? id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
          returnValue: Future<bool>.value(false)) as _i5.Future<bool>);
}

/// A class which mocks [SaveWatchlistTvseries].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveWatchlistTvseries extends _i1.Mock
    implements _i11.SaveWatchlistTvseries {
  MockSaveWatchlistTvseries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvseriesRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvseriesRepository_0()) as _i2.TvseriesRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, String>> execute(
          _i7.TvseriesDetail? tvseries) =>
      (super.noSuchMethod(Invocation.method(#execute, [tvseries]),
              returnValue: Future<_i3.Either<_i6.Failure, String>>.value(
                  _FakeEither_1<_i6.Failure, String>()))
          as _i5.Future<_i3.Either<_i6.Failure, String>>);
}

/// A class which mocks [RemoveWatchlistTvseries].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveWatchlistTvseries extends _i1.Mock
    implements _i12.RemoveWatchlistTvseries {
  MockRemoveWatchlistTvseries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvseriesRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvseriesRepository_0()) as _i2.TvseriesRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, String>> execute(
          _i7.TvseriesDetail? tvseries) =>
      (super.noSuchMethod(Invocation.method(#execute, [tvseries]),
              returnValue: Future<_i3.Either<_i6.Failure, String>>.value(
                  _FakeEither_1<_i6.Failure, String>()))
          as _i5.Future<_i3.Either<_i6.Failure, String>>);
}
